### ISSUE TITLE
Missing Field in version 0.4.0

### ISSUE THREAD

**Issue by manishbassi5** [wnameless/json-flattener#23]
Its working fine with 0.1.0 version but somehow failing with 0.4.0 version. 

Below is the stack trace : 
Caused by: java.lang.NoSuchFieldError: ESCAPE_JSON
	at com.github.wnameless.json.flattener.StringEscapePolicy.<clinit>(StringEscapePolicy.java:46)
	at com.github.wnameless.json.flattener.JsonFlattener.<init>(JsonFlattener.java:109)
	at com.github.wnameless.json.flattener.JsonFlattener.flatten(JsonFlattener.java:88)

**Comment by wnameless** [comment]
Can you provide your code?

**Comment by manishbassi5** [comment]
String flatJsonStr = JsonFlattener.flatten("<json-string>");

I even pasted my exception stack trace above. I think some field is missing in 0.4.0 version.

**Comment by wnameless** [comment]
Actually a blank string is not a valid JSON input.
However I can give you some clues: 
The ESCAPE_JSON is from Apache commons-lang3 library. Did you accidentally exclude it from your project?

**Comment by lebiathan** [comment]
Hi,

I'm facing the exact same problem. Unfortunately, I cannot provide the code but can give a high level overview.

The Json that I'm passing is totally legit. Examples:
- {"en", 0.98}
- {"en": 0.0005, "fr":0.5}

You can think of the above examples (if it helps) as the output of the tika library for language detection (or some version of it). Using a custom parser ( e.g., google's module ), the JSON contents can be parsed just fine.

The code is compiled and then run in HIVE. The moment I do that, I get an exception, with the stracktrace pointing to that very issue:

Caused by: java.lang.NoSuchFieldError: ESCAPE_JSON
    at com.github.wnameless.json.flattener.StringEscapePolicy.<clinit>(StringEscapePolicy.java:46)
    at com.github.wnameless.json.flattener.JsonFlattener.<init>(JsonFlattener.java:109)
    at com.github.wnameless.json.flattener.JsonFlattener.flattenAsMap(JsonFlattener.java:99)


As you may be able to tell from the above code, I'm invoking the static flattenAsMap method.
Line 109 in the JsonFlattener is in fact where you have StringEscapePolicy.

The commons-lang3 jar file is definitely included in the project ( maven project ) and is part of the uber jar that I generate in the end. By doing "jar tf" on the jar, I can see that StringEscapePolicy is in fact there. When checking the contents of that class, which has been added to the uber jar, I can see the field ESCAPE_JSON, but somehow it doesn't get picked up.

Any thoughts on what the issue may be are greatly appreciated.

Also, is the reliance on the commons-lang3 library only for the ESCAPE_JSON field ?

Thanks,
/G

**Comment by manishbassi5** [comment]
@wnameless : I was just giving the example. I am using the valid JSON for sure. Nope. I have not excluded commons-lang3 library from my project.

**Comment by basvdl** [comment]
Today I ran into the same problem... After including the dependency in my pom it was fixed.

<dependency>
    <groupId>org.apache.commons</groupId>
    <artifactId>commons-lang3</artifactId>
    <version>3.5</version>
</dependency>


```
String json = "{\"timestamp\":\"2016-11-11T00:34:01.918498+0100\",\"flow_id\":192435675875106,\"in_iface\":\"eth2\",\"event_type\":\"dns\",\"src_ip\":\"1.1.1.1\",\"src_port\":6995,\"dest_ip\":\"2.2.2.2\",\"dest_port\":21,\"proto\":\"UDP\",\"dns\":{\"type\":\"query\",\"id\":32866,\"rrname\":\"localhost\",\"rrtype\":\"A\",\"tx_id\":0}}";

String flatMessage = new JsonFlattener(json).flatten();
```

**Comment by lebiathan** [comment]
I already have that dependency in my pom file, yet the problem persists. As far as I can tell, there is some sort of conflict with the same class name existing in lang3 version and commons-lang (which is version 2).

Depending on what gets loaded first, the ESCAPE_JSON field may or may not be there.

**Comment by wnameless** [comment]
This problem has been noticed somehow in Apache common-lang3 v3.6.
I've made a update with Apache common-text v1.1 and released a new artifact json-flattener-java7.
The version of json-flattener-java7 will be same as the original json-flattener.
You will need Java7 to use json-flattener-java7 obviously and it should solve the problem of the missing ESCAPE_JSON field.
