### ISSUE TITLE
flatten() creates illegal json when input has null character

### ISSUE THREAD

**Issue by dbirkman-paloalto** [wnameless/json-flattener#42]
When input has a null character:

        String json = "{\"a\":\"b\\u0000c\"}";
        System.out.println("input: " + json);
        System.out.println("output: " + new JsonFlattener(json).flatten());

The output from flatten() is an illegal json:
       
        input: {"a":"b\u0000c"}
        output: {"a":"bc"}

**Comment by wnameless** [comment]
It is not an illegal json.
(A null character usually can't be seen because it's null, but sometimes it is shown as � because the editor treats the null character as an unknown character.)

By default, the null character won't be escaped. If you want to escape the null character, you can provide your own StringEscapePolicy by implementing the CharSequenceTranslatorFactory interface.
