### ISSUE TITLE
Supporting a custom ObjectMapper

### ISSUE THREAD

**Issue by gwayne9955** [wnameless/json-flattener#56]
Supporting a custom `ObjectMapper` (e.g. `.withMapper(ObjectMapper mapper)`) in flatten or unflatten would allow the consumer of the class to define and pass in a mapper to use. It would be particularly useful because `ObjectMapper`s can have custom modules and deserialization/serialization features set.

**Comment by wnameless** [comment]
I know it seems a pretty useful feature, however I don't want the internal implementation details to be exposed to users. 

For example, I changed the core json library from minimal-json to Jackson without jeopardizing the APIs few months ago because I decoupled implementation with interfaces as much as possible.

If I am going to let user to set their favorite json core library in the future, I should figure out a way to abstract the whole json serialization and de-serialization parts in this library.

I will spend some time to think about it.

**Comment by ramkumar-mn** [comment]
As @gwayne9955 commented, it will be really helpful to flatten/unflatten with deserialization/serialization features set.

**Comment by slisaasquatch** [comment]
This is just my opinion, but I'm with @wnameless on this one. I think it is nice for this library to be JSON library agnostic.

**Comment by wnameless** [comment]
Since v0.12.0, new JsonCore is applied to this library. You can now change the internal JSON implementation from Jackson to GSON as well. Please read the new features section in the README.md.

Merry Xmas!
